language: csharp
solution: Expose.sln
mono: none
dotnet: 2.1.502
install:
  - nuget restore Expose.sln
  - nuget install NUnit.Console -Version 3.12.0 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release Expose.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.12.0/tools/nunit3-console.exe ./tests/Expose.NUnit\bin\Release\netcoreapp2.1\Expose.NUnit.dll